In [2]:
import pandas as pd

df = pd.read_csv('dataset/data_semantic.csv')
df.head()
df['plagiarism_type'].unique()

array(['paraphrase', nan, 'verbatim', 'summary'], dtype=object)

In [4]:
df_demo_for_duplicate = pd.concat([df[df["plagiarism_type"] == "verbatim"][:0],
                                   df[df["plagiarism_type"] == "summary"][:25],
                                   df[df["plagiarism_type"] == "paraphrase"][:15],
                                   df[df["plagiarism_type"].isna()][:15]], ignore_index=True)
df_demo_for_duplicate = pd.concat([df_demo_for_duplicate['source_doc'],
                                   df_demo_for_duplicate['susp_doc']], ignore_index=True)
df_demo_for_duplicate = df_demo_for_duplicate.to_frame(name='text')
df_demo_for_duplicate.to_csv('dataset/df_demo_for_duplicate.csv')

df_demo_for_duplicate

                                                  text
0    Motivated by the Internet-of-things and sensor...
1    As a joke, Roy requested an unpopular song to ...
2    Tom drove everyday to work. On day his car bro...
3    The professor began covering the lecture today...
4    We study the problem of allocating a set of in...
..                                                 ...
105  The air was crisp and the leaves of the trees ...
106  I decided to get some exercise. The weather ou...
107  To his surprise, the radio station actually pl...
108  In a surprising display of prosocial behavior,...
109  Her family couldn't afford the tuition fees, a...

[110 rows x 1 columns]

In [27]:
df_ques = pd.read_csv('dataset/dataset_small.csv')
df_demo_for_senmatic = pd.concat([df_ques[df_ques['is_duplicate'] == 1][:30],
                                  df_ques[df_ques['is_duplicate'] == 0][:15]], ignore_index=True)
df_demo_for_senmatic = pd.concat([df_demo_for_senmatic['question1'],
                                  df_demo_for_senmatic['question2']])
df_demo_for_senmatic = df_demo_for_senmatic.to_frame(name='text')
df_demo_for_senmatic.to_csv('dataset/df_demo_for_senmatic.csv')
df_demo_for_senmatic

                                                 text
0   Astrology: I am a Capricorn Sun Cap moon and c...
1                      How can I be a good geologist?
2         How do I read and find my YouTube comments?
3                What can make Physics easy to learn?
4         What was your first sexual experience like?
..                                                ...
40           How do guys feel after rejecting a girl?
41  Which is the best digital marketing institute ...
42   What can I do to avoid being jealous of someone?
43              Which question should I ask on Quora?
44  Where can I find a conversion chart for CC to ...

[90 rows x 1 columns]